### PR TITLE
plugin/kubernetes: Error out when multiple https endpoints are specified.

### LINKED ISSUE #1464: plugin/kubernetes: API connections to secure endpoint list fails
Secure API connections fail if the list of endpoints is > 1. 

See tests in `/coredns/ci/test/kubernetes/excluster_test.go` `TestKubernetesSecureAPIFallthrough`
The test is currently being skipped. coredns/ci#30

### PR DESCRIPTION
**Pull request by yongtang**
### 1. Why is this pull request needed and what does it do?
This fix will error out when multiple https endpoints are specified,
as additional work is needed to support beyond http.

### 2. Which issues (if any) are related?

This fix fixes #1464 and fixes #2429.

### 3. Which documentation changes (if any) need to be made?

Signed-off-by: Yong Tang <yong.tang.github@outlook.com>

### CODE REVIEW

File: plugin/kubernetes/setup.go [hunk 1]
```diff
@@ -196,6 +196,15 @@ func ParseStanza(c *caddy.Controller) (*Kubernetes, error) {
 			args := c.RemainingArgs()
 			if len(args) > 0 {
 				k8s.APIServerList = args
+				if len(args) > 1 {
+					// If multiple endoints specified, then only http allowed
+					for i := range args {
+						parts := strings.SplitN(args[i], "://", 2)
```
Comment (miekg) [inline plugin/kubernetes/setup.go:202]: you can just use url.Parse and check the scheme, seems slightly nicer than using your own "parser"

**Comment by miekg** [comment]
1 nit, otherwise lgtm

**Comment by yongtang** [comment]
@miekg I tried with `url.Parse`, though it is not able to handle situations of `127.0.0.1:8080` where `scheme` field is not included. The following error will thrown out:
```
parse 127.0.0.1:8080: first path segment in URL cannot contain colon
```


```go
ubuntu@ubuntu:/v# go run v.go 
parse 127.0.0.1:8080: first path segment in URL cannot contain colon
ubuntu@ubuntu:/v# cat v.go
package main
import (
	"fmt"
	"net/url"
)
func main() {
	u, err := url.Parse("127.0.0.1:8080")
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(u.Scheme)
	}
}
ubuntu@ubuntu:/v# 
```

**Comment by miekg** [comment]
Ah ok. No problem.

/lgtm

**Review by chrisohaver — APPROVED** [review]
