### PR TITLE
Metrics listener fix

### LINKED ISSUE #1982: plugin/metrics - plugin loose control of the listener after several reloads
On Restart, plugin close the listener and set the uniqAddr to "todo" in order to be restarted on next "onStart: event.

But the SAME function to call is registered, which means on next "uniqAddr.ForEach" the function 'OnStart" of the now old plugin will be called, and the corresponding "onRestart" will never be called.

After 2 reloads, the Listener is no more closed.

### PR DESCRIPTION
**Pull request by ZachEddy**
### 1. Why is this pull request needed and what does it do?

When the metrics address is changed inside the `Corefile` and a reload is triggered, CoreDNS will continue exporting metrics to the old address. This was reported in #1982, so check out that issue for a more in-depth description and some discussion about the bug itself.

This PR  resolves the issue by modifying the metrics plugin's `OnRestart` behavior. Before CoreDNS reloads, the metrics plugin now stops the existing Prometheus exporter and removes the current metrics address from the `Metrics.uniqAddr.Todo` field. When CoreDNS spins back up, it creates `Metrics.uniqAddr` using the new metrics configuration.

### 2. Which issues (if any) are related?
Resolves #1982.

### 3. Which documentation changes (if any) need to be made?

Other than inline documentation, I don't think any documentation changes are necessary; this is just a bug fix.

### CODE REVIEW

File: plugin/pkg/uniq/uniq.go [hunk 1]
```diff
@@ -38,10 +45,11 @@ func (u U) SetTodo(key string) {
 func (u U) ForEach() error {
 	for k, v := range u.u {
 		if v.state == todo {
-			v.f()
+			if err := v.f(); err == nil {
```
Comment (fturib) [inline plugin/pkg/uniq/uniq.go]: What do we do if there is an error here ?
I think this change of code goes with #1868. 

Although it is not wrong, I think it is better to let that change for the PR of that issue.

File: plugin/metrics/metrics.go [hunk 2]
```diff
@@ -138,6 +145,10 @@ func keys(m map[string]bool) []string {
 // we listen on "localhost:0" and need to retrieve the actual address.
 var ListenAddr string
 
+// shutdownTimeout is the maximum amount of time the metrics plugin will wait
+// before erroring when it tries to close the metrics server
+var shutdownTimeout time.Duration = time.Second * 1
```
Comment (fturib) [inline plugin/metrics/metrics.go]: I do not like too much a global var.
I guess we can do a constant for now - is 1 sec enough ?

File: plugin/metrics/metrics.go [hunk 3]
```diff
@@ -94,9 +97,9 @@ func (m *Metrics) OnStartup() error {
 
 	m.mux = http.NewServeMux()
 	m.mux.Handle("/metrics", promhttp.HandlerFor(m.Reg, promhttp.HandlerOpts{}))
-
+	m.srv = &http.Server{Handler: m.mux}
```
Comment (fturib) [inline plugin/metrics/metrics.go:100]: For info : declaring http.Server allow to use Shutdown instead of Close.
and that is mandatory for the UT to work properly.

Good to have the timeout on this shutdown !

**Review by fturib — CHANGES_REQUESTED** [review]
See comments inline.
Thanks for contribution !!

File: plugin/pkg/uniq/uniq.go (hunk 1 above)
Comment (ZachEddy) [reply plugin/pkg/uniq/uniq.go]: Okay! I'll revert `ForEach` back.

File: plugin/metrics/metrics.go (hunk 2 above)
Comment (ZachEddy) [reply plugin/metrics/metrics.go]: > I do not like too much a global var.

Yeah, a constant would be better! I'll update the pull request accordingly.

> is 1 sec enough ?

I chose one second arbitrarily. Since this runs on reload, I figured that a shorter timeout would be better because it could (maybe?) suspend the entire reload process (i.e. a twenty second timeout might block the reload for twenty seconds).

I don't fully understand the reload plugin works and am making some assumptions. Would do you think?

File: plugin/metrics/metrics.go (hunk 3 above)
Comment (ZachEddy) [reply plugin/metrics/metrics.go:100]: Okay cool. I initially tried without the `http.Server` field and saw that it didn't fix the issue, so I figured it had something to do with that 🙂

File: plugin/metrics/metrics.go (hunk 2 above)
Comment (fturib) [reply plugin/metrics/metrics.go]: we expect this timeout is reached only once a while when the server cannot finish its work normally. This server is only about sending data, most of the time fewer than one sec should be enough.

but for extreme case I would set to 5 secs.
Again, we expect the timeout is not used ... and the stop of server happen within the sec.

**Review by fturib — APPROVED** [review]

**Review by grobie — APPROVED** [review]
LGTM

**Comment by fturib** [comment]
@ZachEddy - congrat for your first contribution !
