### PR TITLE
middleware/proxy: remove singleinflight from dns

### LINKED ISSUE #715: All DNS lookups timeout if a proxy is unavailable.
## Observed:
When multiple proxies are being used and one of those proxies is down, all further lookups will stall and likely timeout while the health check is being performed. Once the health check has timed out on its connection attempt (advertised that the "Health check probe failed") further DNS lookups can be made until the next health check cycle at which point lookups will stall again.

## Steps to reproduce:
The best way to reproduce is using AWS instances: 3 'primary' DNS servers running coredns and 1 'secondary' DNS server that will proxy on to the 3 primary DNS servers.
When set up and DNS requests to the secondary DNS server are working, stop one of the primary DNS servers.
This will result in the observed issue and the 'Health check probe' will fail with an i/o timeout error after about 30 seconds.

This can be reproduced in Docker, however, with the way that Docker networking works by manipulating routing tables, stopping containers results in a much shorter timeout of 'no route to host' but the issue can still be observed if DNS requests are quick enough.
Docker compose files are provided below.

docker-compose.yml
```
version: '3'
services:
  coredns-primary-1:
    container_name: coredns-primary-1
    image: coredns/coredns:latest
    networks:
      coredns:
        ipv4_address: 172.16.238.11
    volumes:
      - ./Corefile.primary:/etc/coredns/Corefile
    command: -conf /etc/coredns/Corefile

  coredns-primary-2:
    container_name: coredns-primary-2
    image: coredns/coredns:latest
    networks:
      coredns:
        ipv4_address: 172.16.238.12
    volumes:
      - ./Corefile.primary:/etc/coredns/Corefile
    command: -conf /etc/coredns/Corefile

  coredns-primary-3:
    container_name: coredns-primary-3
    image: coredns/coredns:latest
    networks:
      coredns:
        ipv4_address: 172.16.238.13
    volumes:
      - ./Corefile.primary:/etc/coredns/Corefile
    command: -conf /etc/coredns/Corefile



  coredns-secondary:
    depends_on:
      - coredns-primary-1
      - coredns-primary-2
      - coredns-primary-3
    container_name: coredns-secondary
    image: coredns/coredns:latest
    networks:
      coredns:
        ipv4_address: 172.16.238.21
    volumes:
      - ./Corefile.secondary:/etc/coredns/Corefile
    command: -conf /etc/coredns/Corefile
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"



networks:
  coredns:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
```

Corefile.primary
```
.:53 {
    log stdout
    errors stdout
    health
    proxy . 8.8.8.8:53
}
```

Corefile.secondary
```
.:53 {
    log stdout
    errors stdout
    health
    proxy . 172.16.238.11:53 172.16.238.12:53 172.16.238.13:53 {
        policy round_robin
        fail_timeout 2s
        health_check /health:8080 5s
    }
}
```

DNS query
`watch -n0.1 dig @127.0.0.1 -p 5353 www.google.com`

1. Create docker-compose.yml, Corefile.primary & Corefile.secondary from sections above.
2. `$ docker-compose up -d`
3. `$ docker-compose logs -f coredns-secondary`
4. `$ watch -n0.1 dig @127.0.0.1 -p 5353 www.google.com`
5. Observe DNS requests being made successfully and no health probe errors
6. `$ docker-compose down coredns-primary-1`
7. Observe DNS logging and requests made stop
8. Observe the 'dig watch' time out with "connection timed out; no servers could be reached"
9. Observe the coredns log give a Health probe warning with an i/o timeout, followed by a no route to host error.
10. Observe further DNS requests made and then stop again while health checks are made.

## Sample output
NB: see how the query times go from ms to secons and even minutes after the first health check failure
```
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.472044ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.365466ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.662211ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.627279ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 17.940205ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.571801ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.611922ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:11 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.59918ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.822186ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.868965ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.765292ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.73534ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.540029ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.53002ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.416474ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 18.41688ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:12 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.656563ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.618374ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.797649ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.748291ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.439936ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.826777ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.540117ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.686539ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:13 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.722528ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 18.107535ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.802333ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.705905ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.48139ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.485718ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.552703ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.518026ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.495093ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:14 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.559348ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:15 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.692718ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:15 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.933964ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:52:15 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.613493ms
coredns-secondary    | 2017/06/07 12:52:47 [WARNING] Health check probe failed: Get http://172.16.238.11:8080/health: dial tcp 172.16.238.11:8080: i/o timeout
coredns-secondary    | 2017/06/07 12:53:17 [WARNING] Health check probe failed: Get http://172.16.238.11:8080/health: dial tcp 172.16.238.11:8080: i/o timeout
coredns-secondary    | 2017/06/07 12:53:20 [WARNING] Health check probe failed: Get http://172.16.238.11:8080/health: dial tcp 172.16.238.11:8080: getsockopt: no route to host
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 55.382071728s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 20.042954969s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.042477166s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 30.157539215s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 15.042867535s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 25.157803108s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 35.15825646s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 1m5.38324071s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 40.26801258s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 4.935663729s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 1m0.383373069s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 50.268561952s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 45.268679181s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:20 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 19.665651ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 17.989096ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 20.683365ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.453694ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.99212ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 17.093094ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 18.686241ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.828698ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:21 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.64404ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.420952ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.586984ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.778113ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.684681ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.697002ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:22 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.56975ms
coredns-secondary    | 2017/06/07 12:53:23 [WARNING] Health check probe failed: Get http://172.16.238.11:8080/health: dial tcp 172.16.238.11:8080: getsockopt: no route to host
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:23 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 1.137351305s
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:24 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.678236ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:24 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 10.705543ms
coredns-secondary    | 172.16.238.1 - [07/Jun/2017:12:53:24 +0000] "A IN www.google.com. udp 44 false 4096" NOERROR 60 9.658709ms
```

## Misc
Even more interesting things happen if I use IPTables rules to block all communications with a primary DNS server. It looks like coredns locks up all together with no sign of a timeout.
`iptables -A DOCKER -p all -d 172.16.238.11 -j DROP`

### PR DESCRIPTION
**Pull request by miekg**
Singleinflight interferes with the health checking of upstream. If an
upstream would fail, singleinflight would mirror that error to to other
proxy *iff* multple identical queries would be inflight. This would lead
to marking *all* upstreams as bad, essentially collapsing multiple
upstreams into a SPOF. Clearly not what we want.

Singleinflight does have some nice properties, but I've opted to rip it
out entirely. Caching should almost (but not quite) as good.

Added a test case in test that uses 3 CoreDNS instances to reflect the
setup from #715.

Found another bug as well, where (when the policy would be nil), we
would always Spray even though we've found a healthy host.

Fixes #715

### CODE REVIEW

File: middleware/proxy/dns.go [hunk 1]
```diff
@@ -109,7 +91,7 @@ func exchange(m *dns.Msg, co net.Conn) (dns.Msg, error) {
 
 	dnsco.Close()
 	if r == nil {
-		return dns.Msg{}, err
+		return nil, err
```
Comment (johnbelamaric) [inline middleware/proxy/dns.go:94]: Why is this changed? Are you sure it won't cause a problem from any callers?

**Review by johnbelamaric — COMMENTED** [review]
LGTM, just one question. Also, I am interested to see how this effects performance of proxy in our tests. If our tests were using the same query over and over then it was single-threading them.

File: middleware/proxy/dns.go (hunk 1 above)
Comment (miekg) [reply middleware/proxy/dns.go:94]: The return value was changed back to a pointer, `exchange` was only used from within the single inflight construct so any changes would be very localized.

**Comment by miekg** [comment]
Unrelated: by I'm going to use the Packet servers to setup some benchmarking (go test -bench output).

**Review by johnbelamaric — APPROVED** [review]
