### PR TITLE
plugin/file: fix local CNAME lookup

### LINKED ISSUE #1864: CNAME resolution failing across secondary zones
I believe I'm running into a bug due to having a second zone that could be part of the first zone, so CNAMEs from the first zone aren't being checked against the second zone.

**Scenario:**
Two zones configured as secondaries
  1. example.com
  2. foo.example.com

A CNAME record in example.com that points to an A record in foo.example.com

    bar.example.com. CNAME bar.foo.example.com
    bar.foo.example.com A 192.168.1.1

**The problem:**
Coredns returns the CNAME record to a dig query but not the A record

**Expected result:**
Coredns returns both the CNAME and A record to the dig query

**Dig examples:**

    /etc/coredns # dig @localhost bar.example.com
    
    ; <<>> DiG 9.11.2-P1 <<>> @localhost bar.example.com
    ; (2 servers found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 56085
    ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ; COOKIE: f2701ad5b57f128e (echoed)
    ;; QUESTION SECTION:
    ;bar.example.com.                 IN      A
    
    ;; ANSWER SECTION:
    bar.example.com.          30      IN      CNAME   bar.foo.example.com.
    
    ;; AUTHORITY SECTION:
    example.com.              30      IN      NS      ns1.example.com.
    example.com.              30      IN      NS      ns2.example.com.
    example.com.              30      IN      NS      ns3.example.com.
    example.com.              30      IN      NS      ns4.example.com.
    
    ;; Query time: 0 msec
    ;; SERVER: ::1#53(::1)
    ;; WHEN: Fri Jun 08 00:01:19 UTC 2018
    ;; MSG SIZE  rcvd: 272
    
    
    /etc/coredns # dig @localhost bar.foo.example.com
    
    ; <<>> DiG 9.11.2-P1 <<>> @localhost bar.foo.example.com
    ; (2 servers found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48063
    ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ; COOKIE: 6f0d661a65a5adf5 (echoed)
    ;; QUESTION SECTION:
    ;bar.foo.example.com.           IN      A
    
    ;; ANSWER SECTION:
    bar.foo.example.com.    30      IN      A       192.168.1.1
    
    ;; AUTHORITY SECTION:
    foo.example.com.              30      IN      NS      ns1.example.com.
    foo.example.com.              30      IN      NS      ns2.example.com.
    foo.example.com.              30      IN      NS      ns3.example.com.
    foo.example.com.              30      IN      NS      ns4.example.com.
    
    ;; Query time: 0 msec
    ;; SERVER: ::1#53(::1)
    ;; WHEN: Fri Jun 08 00:03:36 UTC 2018
    ;; MSG SIZE  rcvd: 279

**Working dig example when CNAME and A are reversed**

    /etc/coredns # dig @localhost foo.foo.example.com
    
    ; <<>> DiG 9.11.2-P1 <<>> @localhost foo.foo.example.com
    ; (2 servers found)
    ;; global options: +cmd
    ;; Got answer:
    ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 14960
    ;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 1
    
    ;; OPT PSEUDOSECTION:
    ; EDNS: version: 0, flags:; udp: 4096
    ; COOKIE: 303eaf5099996a90 (echoed)
    ;; QUESTION SECTION:
    ;foo.foo.example.com.              IN      A
    
    ;; ANSWER SECTION:
    foo.foo.example.com.       30      IN      CNAME   foo.example.com.
    foo.example.com.          30      IN      A       192.168.1.1
    
    ;; AUTHORITY SECTION:
    foo.example.com.              30      IN      NS      ns1.example.com.
    foo.example.com.              30      IN      NS      ns2.example.com.
    foo.example.com.              30      IN      NS      ns3.example.com.
    foo.example.com.              30      IN      NS      ns4.example.com.
    
    ;; Query time: 0 msec
    ;; SERVER: ::1#53(::1)
    ;; WHEN: Fri Jun 08 00:28:26 UTC 2018
    ;; MSG SIZE  rcvd: 313
    

**Corefile being used**

    /etc/coredns # cat Corefile
    .:53 {
        cache 30
        errors
        health
        loadbalance round_robin
        log
        prometheus 0.0.0.0:9153
        proxy . /etc/resolv.conf
        secondary example.com {
          transfer from 192.168.2.5
          transfer from 192.168.2.6
          upstream
        }
        secondary foo.example.com {
          transfer from 192.168.2.5
          transfer from 192.168.2.6
          upstream
        }
    }

### PR DESCRIPTION
**Pull request by miekg**
Issue #1864 explains it will, when we serve the child zone as well we
should just recursive into ourself (upstream self). Thus relax the
IsSubDomain check in file/lookup.go and just query (even if the query
will hit a remote server).

I've looped over all other plugins that do something similar (CNAME
resolving) and they didn't do the IsSubDomain check; therefor I've
removed it from *file* as well.

Added test in file_upstream_test that shows this failed before but now
results in a reply.

No documentation changes are needed.

Fixes #1864

### CODE REVIEW

File: plugin/file/lookup.go [hunk 1]
```diff
@@ -380,7 +374,7 @@ func cnameForType(targets []dns.RR, origQtype uint16) []dns.RR {
 func (z *Zone) externalLookup(state request.Request, target string, qtype uint16) []dns.RR {
 	m, e := z.Upstream.Lookup(state, target, qtype)
 	if e != nil {
-		// TODO(miek): debugMsg for this as well? Log?
+		// TODO(miek): Log, or return error here?
```
Comment (SuperQ) [inline plugin/file/lookup.go:377]: Increment an error counter here. :smile:

**Comment by miekg** [comment]
Thanks for reviewing.

>Increment an error counter here. :smile:

Could point. And probably should, but that requires more code as we don't have a 
metrics to use here. We can't use the normal metrics (i.e return an error), 
because there may not be a CNAME target; meaning this isn't error.

Proxy itself might need to export fail/errors

/Miek

--
Miek Gieben
