### PR TITLE
plugin/kubernetes: fix kubernetes in-cluster CNAME lookup

### LINKED ISSUE #2038: Kubernetes service external-name link to another namespaces service not work.
kubernetes plugin can not resolve service which using `externalName` to link another service. I guess this issue is similar to #1866 .

Cluster using `kubedns` cannot reproduce this issue.

### How to reproduce

```
➜  kubectl get svc  # there is a service in default namespace named `kubernetes`
NAME          TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
kubernetes    ClusterIP   172.21.0.1     <none>        443/TCP    9d

➜  kubectl create -f -<<EOF # create a service link to service in default namespace
heredoc> kind: Service
apiVersion: v1
metadata:
  name: servicetest
  namespace: testdns
spec:
  type: ExternalName
  externalName: kubernetes.default.svc.cluster.local
heredoc> EOF
service "servicetest" created

➜  kubectl run -it --image registry.aliyuncs.com/wangbs/netdia --namespace testdns --rm busybox 
If you don't see a command prompt, try pressing enter.
/ # ping kubernetes.default.svc.cluster.local # `kubernetes` service can resolved directly
PING kubernetes.default.svc.cluster.local. (172.21.0.1): 56 data bytes
^C
--- kubernetes.default.svc.cluster.local. ping statistics ---
2 packets transmitted, 0 packets received, 100% packet loss

/ # ping servicetest.testdns.svc.cluster.local # service linked to `kubernetes` cannot resolved
ping: bad address 'servicetest.testdns.svc.cluster.local'

```

### kubernetes version && coredns version

k8s=1.10.4
coredns=1.2.0

### PR DESCRIPTION
**Pull request by BSWANG**
### 1. Why is this pull request needed and what does it do?

When using kubernetes plugin to do recursive CNAME lookup. If the CNAME target also in kubernetes zone. The kubernetes plugin will fail because of zone is not set, the kubernetes' zone cannot be cutoff from query name, then cannot found from kubernetes service & pod:

So I pass the zone to backend plugin, when state name not belong to the zone passed in. Then the kubernetes plugin will fail to next plugin.

### 2. Which issues (if any) are related?
fix #2038 

### 3. Which documentation changes (if any) need to be made?

none

### CODE REVIEW

**Comment by BSWANG** [comment]
Look like some unit test in etcd plugin failed. I will fix it soon.

**Review by chrisohaver — CHANGES_REQUESTED** [review]
Thanks.  Please add a unit test.

**Comment by BSWANG** [comment]
@chrisohaver I have added unit test for those changes.

File: plugin/kubernetes/parse_test.go [hunk 1]
```diff
@@ -14,17 +14,17 @@ func TestParseRequest(t *testing.T) {
 		expected string // output from r.String()
 	}{
 		// valid SRV request
-		{"_http._tcp.webs.mynamespace.svc.inter.webs.test.", "http.tcp..webs.mynamespace.svc"},
+		{"_http._tcp.webs.mynamespace.svc.inter.webs.tests.", "http.tcp..webs.mynamespace.svc"},
```
Comment (chrisohaver) [inline plugin/kubernetes/parse_test.go:17]: Why are these changes necessary?  `test` => `tests`

Comment (BSWANG) [reply plugin/kubernetes/parse_test.go:17]: Yes, this is a typo before. The query zone is `inter.webs.tests`,but domain use `*.inter.webs.test` which query name doesn't belong to kubernetes zone. 
 https://github.com/coredns/coredns/blob/8aa55c5ff2f30b2d4b4c5faad5e0a465648f9736/plugin/kubernetes/parse_test.go#L62

When add the query domain name check in kubernetes plugin. Those typos will cause unittest fail.

File: plugin/kubernetes/parse.go [hunk 2]
```diff
@@ -33,7 +33,9 @@ func parseRequest(state request.Request) (r recordRequest, err error) {
 	// 3. (service): service.namespace.pod|svc.zone
 	//
 	// Federations are handled in the federation plugin. And aren't parsed here.
-
+	if !dns.IsSubDomain(state.Zone, state.Name()) {
```
Comment (chrisohaver) [inline plugin/kubernetes/parse.go]: I dont think this can happen.  `state.Zone` is taken from the query name in Kubernetes.ServeDNS,...

```
	zone := plugin.Zones(k.Zones).Matches(state.Name())
	if zone == "" {
		return plugin.NextOrFailure(k.Name(), k.Next, ctx, w, r)
	}

	state.Zone = zone
```

So this check is not necessary.

Comment (BSWANG) [reply plugin/kubernetes/parse.go]: The recursive CNAME lookup will not call `Kubernetes.ServeDNS` function. Just call `Kubernetes.Services`. So this zone will not be checked. When use a query which cname to external name will not be checked then not be redirected to next plugin.

Comment (chrisohaver) [reply plugin/kubernetes/parse.go]: Ah, right, but the vast majority of the time it's redundant...  Perhaps move this to the back end.

Comment (BSWANG) [reply plugin/kubernetes/parse.go]: Move this check to Kubernetes.Service when lookup  A ?

Comment (chrisohaver) [reply plugin/kubernetes/parse.go]: I meant backend_lookup.go, to check before recursing.  e.g. if the CNAME target is not in the state.Zone, dont try to recurse in the current plugin. 

Do tests fail if you remove this check?

Comment (BSWANG) [reply plugin/kubernetes/parse.go]: Yes, If I move the check to backend_lookup.go, Will break the etcd testcases. 

```
=== RUN   TestOtherLookup
--- FAIL: TestOtherLookup (0.04s)
	helpers.go:131: Additional for "a.mail.skydns.test." contained 0 results, 2 expected
	helpers.go:301: ;; opcode: QUERY, status: NOERROR, id: 38075
		;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
		
		;; QUESTION SECTION:
		;a.mail.skydns.test.	IN	 MX
		
		;; ANSWER SECTION:
		a.mail.skydns.test.	300	IN	MX	50 mx.skydns.test.
```

**Comment by BSWANG** [comment]
@chrisohaver 
 If I move the check to backend_lookup.go, Will break the etcd testcases.

=== RUN   TestOtherLookup
--- FAIL: TestOtherLookup (0.04s)
	helpers.go:131: Additional for "a.mail.skydns.test." contained 0 results, 2 expected
	helpers.go:301: ;; opcode: QUERY, status: NOERROR, id: 38075
		;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
		
		;; QUESTION SECTION:
		;a.mail.skydns.test.	IN	 MX
		
		;; ANSWER SECTION:
		a.mail.skydns.test.	300	IN	MX	50 mx.skydns.test.
Because of the dns.IsSubDomain("skydns.test.", "cname2.region2.skydns.test") return false. 😓Then the recursive query will break. Should I fix this `dns.IsSubDomain` bug first?

**Comment by BSWANG** [comment]
@chrisohaver 
I modify the etcd tests domain, remove the end dot in CNAME test to walkaround the `dns.IsSubDomain` bug.

**Comment by BSWANG** [comment]
@chrisohaver I moved the zone check to `backend_lookup.go`.

**Comment by chrisohaver** [comment]
> I moved the zone check to backend_lookup.go.

Also probably needs to be added to `AAAA`.   And possibly others... not sure about which ones, but any record type that has CNAME lookup code in it should get this.

**Comment by chrisohaver** [comment]
With your change, I believe this check becomes redundant...

https://github.com/coredns/coredns/pull/2040/files#diff-58181e241bb9f530b723f1e33ad55d7dR59

**Comment by BSWANG** [comment]
@chrisohaver I have removed the redundant code. And check others query type's code, `AAAA` need this fix code and I added same logic to it. Others query types `MX` & `SRV`... already have the `IsSubDomain` check.

**Review by chrisohaver — APPROVED** [review]

File: plugin/backend_lookup.go [hunk 3]
```diff
@@ -110,19 +108,20 @@ func AAAA(b ServiceBackend, zone string, state request.Request, previousRecords
...
-
-			state1 := state.NewWithQuestion(serv.Host, state.QType())
-			nextRecords, err := AAAA(b, zone, state1, append(previousRecords, newRecord), opt)
-
-			if err == nil {
-				// Not only have we found something we should add the CNAME and the IP addresses.
-				if len(nextRecords) > 0 {
-					records = append(records, newRecord)
-					records = append(records, nextRecords...)
+			if dns.IsSubDomain(zone, dns.Fqdn(serv.Host)) {
```
Comment (miekg) [inline plugin/backend_lookup.go:111]: this dns.Fqdn is superfluous and the one above as well. Was there any reason to add them?

Comment (miekg) [reply plugin/backend_lookup.go:111]: Hmm, there were there before *shrug*

Comment (BSWANG) [reply plugin/backend_lookup.go:111]: @miekg The etcd unit test will failed if I remove dns.Fqdn. Because of "CNAME" target isn't ends with '.'.
https://github.com/coredns/coredns/blob/75f1b9c988e036a56f0ae31224401aa9b652e9ef/plugin/etcd/cname_test.go#L53-L60
