### PR TITLE
plugin/sign: fix signing of authoritative data

### LINKED ISSUE #3354: plugin/sign: add Walk to exclude children and glue
The Walk function used in *sign* currently signs glue (is has a BUG section in the README). Fix this to exclude it, so we currently sign any zone - even those with subdomains.

### PR DESCRIPTION
**Pull request by miekg**
Don't sign data we are not authoritative for. This adds an AuthWalk
which skips names we should not authoritative for. Adds a few tests to
check this is the case. Generates zones have been compared to
dnssec-signzone.

A number of changes have been made:

* don't add DS records to the apex
* NSEC TTL is the SOA's minttl value (copying bind9)
* Various cleanups

Fixes: #3354

Bulk of the code is new tests cases. The gist is file/tree/authwalk.go and sign/signer.go

Signed-off-by: Miek Gieben <miek@miek.nl>

### CODE REVIEW

File: plugin/file/tree/walk.go [hunk 1]
```diff
@@ -2,25 +2,28 @@ package tree
 
 import "github.com/miekg/dns"
 
-// Walk performs fn on all values stored in the tree. If a non-nil error is returned the
-// Walk was interrupted by an fn returning that error. If fn alters stored values' sort
+// Walk performs fn on all authoritative values stored in the tree in
+// pre-order depth first. If a non-nil error is returned the Walk was interrupted
```
Comment (chrisohaver) [inline plugin/file/tree/walk.go]:
```suggestion
// in-order depth first. If a non-nil error is returned the Walk was interrupted
```

**Comment by chrisohaver** [comment]
@miekg, I'm finding I need to familiarize my self with DNSSEC before I can understand the PR and do a full/fair review.
This will slow my review.  If you'd prefer a faster code review, feel free to rope in others.

File: plugin/file/tree/auth_walk.go [hunk 2]
```diff
@@ -0,0 +1,58 @@
+package tree
+
+import (
+	"github.com/miekg/dns"
+)
+
+// AuthWalk performs fn on all authoritative values stored in the tree in
+// pre-order depth first. If a non-nil error is returned the AuthWalk was interrupted
```
Comment (chrisohaver) [inline plugin/file/tree/auth_walk.go]:
```suggestion
// in-order depth first. If a non-nil error is returned the AuthWalk was interrupted
```

Comment (chrisohaver) [inline plugin/file/tree/auth_walk.go:8]:
```suggestion
// in-order depth first. If a non-nil error is returned the AuthWalk was interrupted
```

File: plugin/file/tree/auth_walk.go [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+func (n *Node) authwalk(ns map[string]struct{}, fn func(*Elem, map[uint16][]dns.RR, bool) error) error {
+	if n.Left != nil {
+		if err := n.Left.authwalk(ns, fn); err != nil {
+			return err
+		}
+	}
+
+	// Check if the current name is a subdomain of *any* of the delegated names we've seen, if so, skip this name.
+	// The ordering of the tree and how we walk if guarantees we see parents first.
+	if n.Elem.Type(dns.TypeNS) != nil {
```
Comment (chrisohaver) [inline plugin/file/tree/auth_walk.go:30]: Will this tag the origin/apex as delegated?  Does this need check to see if `n.Elem.Name() == origin`?
maybe by checking for an SOA? e.g. `n.Elem.Type(dns.TypeNS) != nil && n.Elem.Type(dns.TypeSOA) == nil`

Comment (miekg) [reply plugin/file/tree/auth_walk.go:30]: Yes, this is a bit icky; i will not by virtue for zones as these apex records somewhere else: https://github.com/coredns/coredns/blob/master/plugin/file/zone.go#L24

**Review by chrisohaver — APPROVED** [review]
LGTM - Although I don't yet fully understand NSEC type bitmaps, and therefore can't verify that change.  But otherwise LGTM.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] plugin/sign: ..." ]
>chrisohaver approved this pull request.
>
>LGTM - Although I don't yet fully understand NSEC type bitmaps, and therefore can't verify that change.  But otherwise LGTM.

Thanks. I'm running this on my personal server and done some checks. I'll
inspect more, but it should be good (fingers crossed).
