### PR TITLE
reload: use OnRestart

### LINKED ISSUE #1604: plugin/health plugin/prometheus graceful restart bug
Tested on 3e3d8cc845b8e072efc75043c9aa3df318ec3bf3 with Corefile
```
.:53 {
	health 127.0.0.1:8080
	proxy . 8.8.8.8:53
}
```
After graceful restart with "killall -USR1 coredns" we get an error:
```
[INFO] SIGUSR1: Reloading
[INFO] Reloading
[ERROR] SIGUSR1: listen tcp 127.0.0.1:8080: bind: address already in use
```

### PR DESCRIPTION
**Pull request by miekg**
Close the listener on OnRestart for health and metrics so the default
setup function can setup the listener when the plugin is "starting up".

Lightly test with some SIGUSR1-ing. Also checked the reload plugin with
this, seems fine:

.com.:1043
.:1043
2018/04/20 15:01:25 [INFO] CoreDNS-1.1.1
2018/04/20 15:01:25 [INFO] linux/amd64, go1.10,
CoreDNS-1.1.1
linux/amd64, go1.10,
2018/04/20 15:01:25 [INFO] Running configuration MD5 = aa8b3f03946fb60546ca1f725d482714
2018/04/20 15:02:01 [INFO] Reloading
2018/04/20 15:02:01 [INFO] Running configuration MD5 = b34a96d99e01db4015a892212560155f
2018/04/20 15:02:01 [INFO] Reloading complete
^C2018/04/20 15:02:06 [INFO] SIGINT: Shutting down

With this corefile:
.com {
  proxy . 127.0.0.1:53
  prometheus :9054
  whoami
  reload
}

. {
  proxy . 127.0.0.1:53
  prometheus :9054
  whoami
  reload
}

The prometheus port was 9053, changed that to 54 so reload would pick it
up.

From a cursory look it seems this also fixes:
Fixes #1604 #1706

### CODE REVIEW

**Comment by rdrozhdzh** [comment]
see my comment https://github.com/coredns/coredns/issues/1604#issuecomment-383125368

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] reload: use O..." ]
>see my comment https://github.com/coredns/coredns/issues/1604#issuecomment-383125368

Well, true, but we in a rock and hard place, and the complexity of #1688 is 
terrifying IMO.

This can leave with a closed listener which means - crash? (have to test). Note 
the a failed reload is already pretty severe.

**Comment by rdrozhdzh** [comment]
Yes, the problem I mentioned (failed to start new instance) is rather hypothetical, we first need to fix #1688 since it affects lot of people

**Comment by miekg** [comment]
Hmmm, failing to reload is rather odd (from the logging):
~~~
.com.:1043
.:1043
2018/04/20 15:29:00 [INFO] CoreDNS-1.1.1
2018/04/20 15:29:00 [INFO] linux/amd64, go1.10, 21bb5dcb-dirty
CoreDNS-1.1.1
linux/amd64, go1.10, 21bb5dcb-dirty
2018/04/20 15:29:00 [INFO] Running configuration MD5 = b34a96d99e01db4015a892212560155f
2018/04/20 15:29:36 [INFO] Reloading
2018/04/20 15:29:36 [ERROR] Failed to start metrics handler: listen tcp :443: bind: permission denied
2018/04/20 15:29:36 [INFO] Running configuration MD5 = 45fdd9451627040d94a86e08a6adaeed
2018/04/20 15:29:36 [INFO] Reloading complete
~~~
So it reloaded?

**Comment by miekg** [comment]
I think #1668 is adding too much complexity, we we may need at some point; right now this (not 100% solution - I agree) is at least helping in the happy path...

**Comment by fturib** [comment]
The point is that the order of event is not very convenient in CoreDNS use case.
We would need that the new Caddyfile is validated BEFORE stopping in any way the former server.
But right now : "onRestart" is called before any check on the new Corefile.

### 1- Allow listeners to not be reloaded

So if the new Corefile has a syntax error, then HELATH and PROMETHEUS will not work anymore until a valid Corefile is reloaded.
Is that good enough ? 

### 2- keep listener with address defined at first load (reload is kind of ignored for the HTTP service)

Another shortcut would be to adapt the HEALTH/PLUGIN to not reload the listeners .. and keep the initial Listening configuration. (change of code would be only in the Plugins).

### 3 - Reuse a first proposition that mostly works but does not handle some corner cases

There is a PR that can fix that issue : #1621, it was the first one I proposed few weeks ago. It is much simpler than #1688, but has some drawback if you reuse the ports from one plugin to another.
let me know if you think that could work as temporary before the #1688 is fully validated.

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/coredns] reload: use O..." ]
>The point is that the order of event is not very convenient in CoreDNS use case.
>We would need that the new Caddyfile is validated BEFORE stopping in any way the former server.
>But right now : "onRestart" is called before any check on the new Corefile.

Yes, I'm aware of the trade off that have to made here. And this isn't a 100% 
solution either. But consider this:

* the failure modes are clear; reload work, but you may loose your listener. 
  This is really bad, but then again you were asking coredns for the impossible
* The code is supershort
* It solves all *initial* bug reports

**Comment by miekg** [comment]
just a though: but with the reload plugin we should be able to test this actually.

File: plugin/health/health.go [hunk 1]
```diff
@@ -61,6 +61,17 @@ func (h *health) OnStartup() error {
...
+			return err
+		}
+		h.ln = nil
+	}
+	return nil
+}
+
 func (h *health) OnShutdown() error {
 	// Stop polling plugins
 	h.pollstop <- true
```
Comment (fturib) [inline plugin/health/health.go]: The lameduck part should happen on RESTART ?
I would think only on FINAL shutdown.

That means maybe having a separated function to close Listener and to process the Lameduck.

OnRestart -> close listener
OnFinalShutdown -> close listener + lameduck delay

File: plugin/metrics/metrics.go [hunk 2]
```diff
@@ -104,6 +104,18 @@ func (m *Metrics) OnStartup() error {
...
+	// relingish our listener as we re-listen on successfull reload
+	if m.ln != nil {
+		if err := m.ln.Close(); err != nil {
+			return err
+		}
+		m.ln = nil
+	}
+	return nil
+}
+
```
Comment (fturib) [inline plugin/metrics/metrics.go]: So.. the OnRestart is the same (a little proper) than the OnShutdown .. no ? Maybe we can have only one to be called for the 2 events:
- onRestart
- onFinalShutdown
I would not report the error to Caddy as it will prevent to continue the RESTART or SHUTDOWN. Anyway if the listener cannot be closed it means it is already closed. Maybe INFO the  error.

NOTE: onShutdown works too .. but is confusing for the reader.

**Comment by miekg** [comment]
https://github.com/coredns/coredns/pull/1710 has a test, I'll rework stuff during the weekend (unless your branch from the PR - fine with me) and get into a state where we can merge (also needs some doc updates in the reload plugin and else where).

File: plugin/reload/README.md [hunk 3]
```diff
@@ -59,3 +60,27 @@ Check every 10 seconds (jitter is automatically set to 10 / 2 = 5 in this case):
...
+~~~
+
+CoreDNS starts and serves health from :8080. Now you change `:8080` to `:443` not knowing a process
+is already listening on that port. The process reloads, and performs the following steps:
+
+1. close the listener on 8080
+2. reload and parse the config again
+3. fail to start a new listener on 443
+
+Now failing step 3 *does not cause* the reload to fail, instead almost everything works, except the
```
Comment (fturib) [inline plugin/reload/README.md]: Are you sure ?
I think that if the Listener fails to start on 443, then OnStartup will return an error, that will be returned back to Caddy .. and the Start of the new server will just fail, leading to the fail of Restart().

The old server will keep running, but the Listener will be closed on :8080

File: plugin/reload/README.md [hunk 4]
```diff
@@ -59,3 +60,27 @@ Check every 10 seconds (jitter is automatically set to 10 / 2 = 5 in this case):
...
+health exporting because there is no new listener.
+
+Note the same is true for prometheus metrics plugin.
```
Comment (fturib) [inline plugin/reload/README.md]: Right now, plugin METRICS is a strange animal : if you shutdown a listener, it will never restart on the same address ! (because the started listeners are saved in a global var map).
=> it is maybe better to close only on "OnFinalShutdown" and do not consider changing the address.

Comment (miekg) [reply plugin/reload/README.md]: The reason that was done was to support both:
~~~
.com {
   prometheus
}
.net {
   prometheus
}
~~~

and

.com {
   prometheus :1200
}
.net {
   prometheus :8080
}
~~~
Maybe we should just give up no that or find a better way.

**Comment by miekg** [comment]
Explicitly not support in the health middleware
~~~
If you have multiple Server Blocks and need to export health for each of the plugins, you must run
health endpoints on different ports:
~~~
For the prometheus plugin that global uniqAddr is uses precisely for this reason.

File: plugin/reload/README.md (hunk 3 above)
Comment (miekg) [reply plugin/reload/README.md]: changed

**Comment by miekg** [comment]
Ok, this ballooned into way more LOCs then expected :-(
Trying to trim it a little now the tests pass.

PTAL

File: plugin/metrics/setup.go [hunk 5]
```diff
@@ -15,7 +15,7 @@ func init() {
 		Action:     setup,
 	})
 
-	uniqAddr = addrs{a: make(map[string]int)}
+	uniqAddr = newAddress()
```
Comment (fturib) [inline plugin/metrics/setup.go:18]: I think for Metrics the issue is here : Addresses is a global var that register addrss of listeners for metrics. 
- at Setup : new addrs goes as "todo"
- as Startup : this address is processed - listener is created and "todo" goes into "done"
- at Restart : the listener is closed
- at Setup again (restart)... the addrs is already "done" - no change
- as Startup : nothing happen as the addrs is "done- 

**AFTER RESTART if address does not change, the listener of prometheus is just not listening**

Comment (fturib) [reply plugin/metrics/setup.go:18]: A short term easy mitigation : do not shutdown the listener at "OnRestart", but only at "OnFinalShutdown".

=> premetheus will not be very compatible with reload, but will not prevent it.

**Review by fturib — COMMENTED** [review]
I think should work for HEALTH.
but for METRICS, see my comment : I guess you can reload, but I think you cannot collect data on the listener after RESTART (see my comment)

File: plugin/metrics/setup.go (hunk 5 above)
Comment (fturib) [reply plugin/metrics/setup.go:18]: Did you make a try, running Coredns with health, and Prometheus, reloading and verifying you can still collect HEALTH and METRICS on the correct IP ?

Comment (miekg) [reply plugin/metrics/setup.go:18]: OK, done the following test - I can prolly actually make a Go test for this as well. Anway:

Corefile:
~~~
. {
    errors
    log
    prometheus :35053
    whoami
    health :35080
}
~~~
Start `./coredns -dns.port=1043`; query it for metrics to be published. Then
~~~
% curl http://localhost:35080/health
OK%
~~~
and
~~~
% curl -s http://localhost:35053/metrics|head -3
# HELP coredns_build_info A metric with a constant '1' value labeled by version, revision, and goversion from which CoreDNS was built.
# TYPE coredns_build_info gauge
coredns_build_info{goversion="go1.10.1",revision="",version="1.1.1"} 1
~~~
restart:
~~~
% kill -SIGUSR1 $(pidof coredns) 
2018/04/21 16:18:15 [INFO] SIGUSR1: Reloading
2018/04/21 16:18:15 [INFO] Reloading
2018/04/21 16:18:15 [INFO] Reloading complete
~~~
metrics indeed *dead*
health works: 

~~~
% curl -s http://localhost:35080/health
OK% 
~~~

Nice find!

Comment (miekg) [reply plugin/metrics/setup.go:18]: Trying another fix that sets the m.Addr to todo again.

**Comment by miekg** [comment]
travis is extremely flacky for me on testing this pr :/

**Comment by miekg** [comment]
Ok, squashed some commits to kick off another travis check; seems OK now.

not super perfect; but good enough IMO. @fturib PTAL

**Comment by fturib** [comment]
Great Miek ! I think you are good with the tests. 
Code looks good for me.

The only drawbacks we have for now, and can be addressed later:
Health or Metrics listeners may not be operational after a failed RESTART, until the next successful RESTART

**Comment by miekg** [comment]
yes, I tried to document that in plugin/reload/README.md in the bugs section or you pointing to *another* issue? (but even so, file another issues :) )

**Review by fturib — APPROVED** [review]
LGTM.
