### PR TITLE
plugin/kubernetes: Handle endpoint tombstones

### LINKED ISSUE #3860: CoreDNS pods panic with no probe failures
**What happened**:

Recently, we have seen CoreDNS pods panic with no probe failures.  The pod logs show a panic and error yet there are no liveness nor readiness probe failures.  As a result, the pod isn't working and isn't restarted thus leading to DNS failures within the cluster.

**Pod liveness probe:**
```
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
```

**Pod readiness probe:**
```
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 8181
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
```

**What you expected to happen**:

CoreDNS liveness probe detects that the CoreDNS pod has failed and restarts it.

**How to reproduce it (as minimally and precisely as possible)**:

We don't have an easy recreate scenario.  The problem may be triggered by master network connectivity flakes.

**Anything else we need to know?**:

No.

**Environment**:

- the version of CoreDNS: 1.6.7 and 1.6.9
- Corefile: See below
- logs, if applicable: Not available
- OS (e.g: `cat /etc/os-release`): Ubuntu 18.04.4 LTS
- Others: Failures seen on IBM Cloud Kubernetes Service clusters running Kubernetes version 1.16 and 1.17.

```
    .:53 {
        errors
        health {
            lameduck 10s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
```

### PR DESCRIPTION
**Pull request by chrisohaver**
### 1. Why is this pull request needed and what does it do?

`ToEndpoints()` conversion was filtering out Endpoint deletion tombstones (where the object in the event is not an `*api.Endpoint`, but rather a `cache.DeletedFinalStateUnknown`).  The tombstones are essentially indicators that the Endpoint was deleted, without a containing a full copy of the Endpoints object - just a key value.  `ToEndpoints()`  was returning a nil `*object.Endpoints` when these were encountered, which caused failures downstream when deleting from the index.

This fix is allows `ToEndpoints()` to pass the tombstones through, so they can be deleted properly from the `clientState`.

### 2. Which issues (if any) are related?

Fixes #3860

### 3. Which documentation changes (if any) need to be made?

none

### 4. Does this introduce a backward incompatible change or deprecation?

no

### CODE REVIEW

**Comment by miekg** [comment]
thanks @chrisohaver . Was this knowable at the time when we did the refactoring to make the memory go down?
I think this warrants a copy of your commit message into the source code to warn future devs - possible pointing to code and or documentation this is a thing

**Comment by chrisohaver** [comment]
Looks like this may have been an issue since CoreDNS 1.2.3, when API object trimming was introduced. I would _not_ recommend reverting back to a version before 1.2.3 to avoid this bug.

This bug should be relatively uncommon to encounter, however some things that could increase occurrence:
- unstable network resulting in extended periods of disconnect between CoreDNS and k8s API.
- a short etcd compaction interval in the k8s api server

**Comment by chrisohaver** [comment]
> Was this knowable at the time when we did the refactoring to make the memory go down?

Theoretically? Probably.
Reasonably?  Not sure.  client-go is complex.

> I think this warrants a copy of your commit message into the source code

Makes sense. I'll add it in `ToEndpoints()`.

File: plugin/kubernetes/object/endpoint.go [hunk 1]
```diff
@@ -44,10 +44,10 @@ type EndpointPort struct {
 func EndpointsKey(name, namespace string) string { return name + "." + namespace }
 
 // ToEndpoints converts an api.Endpoints to a *Endpoints.
-func ToEndpoints(obj interface{}) (*api.Endpoints, *Endpoints) {
+func ToEndpoints(obj interface{}) (*api.Endpoints, interface{}) {
```
Comment (johnbelamaric) [inline plugin/kubernetes/object/endpoint.go]: This is kind of a weird change. I think it would be more readable if we changed the signature to `func ToEndpoints(*api.Endpoints) (*Endpoints)`, do the casting in the caller, and just not call it if `obj` is not a `*api.Endpoints`.

Comment (johnbelamaric) [reply plugin/kubernetes/object/endpoint.go]: Assuming as I believe `ToEndpoints` is only called once anyway.

Comment (chrisohaver) [reply plugin/kubernetes/object/endpoint.go]: yeah - i was just making this change. :)

File: plugin/kubernetes/object/endpoint.go [hunk 2]
```diff
@@ -44,12 +44,7 @@ type EndpointPort struct {
 func EndpointsKey(name, namespace string) string { return name + "." + namespace }
 
 // ToEndpoints converts an api.Endpoints to a *Endpoints.
-func ToEndpoints(obj interface{}) (*api.Endpoints, *Endpoints) {
-	end, ok := obj.(*api.Endpoints)
-	if !ok {
-		return nil, nil
-	}
-
+func ToEndpoints(end *api.Endpoints) (*api.Endpoints, *Endpoints) {
```
Comment (johnbelamaric) [inline plugin/kubernetes/object/endpoint.go]: I still don't get why we pass in `end` and then just return it.

Comment (johnbelamaric) [reply plugin/kubernetes/object/endpoint.go]: I mean, why do we need to return it?

Comment (chrisohaver) [reply plugin/kubernetes/object/endpoint.go]: > I mean, why do we need to return it?

You're right.  I should do more refactoring here...

**Comment by chrisohaver** [comment]
I've further jostled the code around to reduce verbosity and scope of changes.
... need to retest it to verify things still work. (checked)

**Comment by zouyee** [comment]
Many controllers have examples of handling this scenario

https://github.com/kubernetes/kubernetes/blob/f975b4b0dff48c6a580593f3bc05220c70afa367/pkg/controller/disruption/disruption.go#L363-L379

**Comment by chrisohaver** [comment]
> Many controllers have examples of handling this scenario

Yes, I have essentially based this change on such examples.

**Comment by chrisohaver** [comment]
The latest iteration moves the delta object inspection to inside the switch cases.  I think it reads better.  Note that now it sends the (possibly outdated) endpoints object from the tombstone to `store.Delete()` instead of passing in the tombstone itself (as is done in client-go's informer processor, from where this was originally copied), but this is ok , because Delete only uses immutable key fields.

File: plugin/kubernetes/controller.go [hunk 3]
```diff
@@ -163,17 +166,40 @@ func newdnsController(ctx context.Context, kubeClient kubernetes.Interface, opts
...
+								// up-to date copy of the Endpoints object. We need to use cache.DeletedFinalStateUnknown
+								// object so it can be properly deleted by store.Delete() below, which knows how to handle it.
+								tombstone, ok := d.Object.(cache.DeletedFinalStateUnknown)
+								if !ok {
+									return errors.New("expected tombstone")
+								}
+								if err := clientState.Delete(tombstone); err != nil {
+									return err
+								}
+								apiEndpoints, ok = tombstone.Obj.(*api.Endpoints)
```
Comment (johnbelamaric) [inline plugin/kubernetes/controller.go:184]: I don't fully understand this, why do we need this part if we already deleted it with the tombstone?

Comment (chrisohaver) [reply plugin/kubernetes/controller.go:184]: It hasn't been deleted yet at this point. It gets deleted later with `clientState.Delete(obj)`.  If we don't call `clientState.Delete`, it will remain in the cache.

**Comment by chrisohaver** [comment]
Not sure why I have not seen this for Service objects in my tests - perhaps the API doesn't send tombstones for Service objects, just the endpoints. 

I have not tested Pods, but I suspect we'll see this issue there too.  But I want to get this PR squared away in a state that is acceptable before replicating it to Pods and Services.

File: plugin/kubernetes/controller.go (hunk 3 above)
Comment (johnbelamaric) [reply plugin/kubernetes/controller.go:184]: So what does `clientState.Delete(tombstone)` do?

Comment (chrisohaver) [reply plugin/kubernetes/controller.go:184]: arg! - I left that in by accident.  Thanks for catching that. I'll remove it and run the test again.

**Comment by johnbelamaric** [comment]
Ok, that looks better!

**Comment by ekeih** [comment]
Thanks for your work on that @chrisohaver! This fix will make live easier for us, we recently saw this issue a lot on clusters running in Azure VMs.
I don't know how the release cycle/management of coredns usually works. Is there any way to get a patch release in the near future? Or do you release in fixed intervals?
